// @ts-check
/**
 * @fileoverview End-to-End tests for full Sauron workspace initialization and runtime generation.
 * Adheres strictly to testing-principles and write-a-test:
 * - Tests full user journey in an isolated real-world workspace.
 * - Enforces idempotency (AP-16 prevention: zero state bleeding).
 * - Verifies file content non-emptiness and rule injection.
 */

import { describe, it, before, after } from "node:test";
import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);
const CLI_PATH = path.resolve("bin", "sauron.mjs");

describe("E2E: Workspace Bootstrap & Transpilation (init-workspace)", () => {
  /** @type {string} */
  let tempWorkspace;

  before(() => {
    // Arrange: Create realistic developer project
    tempWorkspace = fs.mkdtempSync(path.join(os.tmpdir(), "sauron-e2e-init-"));
    fs.writeFileSync(
      path.join(tempWorkspace, "package.json"),
      JSON.stringify(
        {
          name: "e2e-test-app",
          version: "0.1.0",
          type: "module",
        },
        null,
        2,
      ),
      "utf8",
    );
  });

  after(() => {
    // Teardown: Clean up isolated workspace
    if (fs.existsSync(tempWorkspace)) {
      fs.rmSync(tempWorkspace, { recursive: true, force: true });
    }
  });

  it("bootstraps sauron in a new workspace, creating config and 17 runtimes", async () => {
    // Act: Execute sauron init
    const { stdout } = await execFileAsync("node", [CLI_PATH, "init"], {
      cwd: tempWorkspace,
    });

    // Assert: Check CLI console feedback
    assert.ok(
      stdout.includes("sauron.config.yaml created") ||
        stdout.includes("CONFIG"),
      "Must log config creation",
    );

    // Assert: Verify sauron.config.yaml creation
    const configPath = path.join(tempWorkspace, "sauron.config.yaml");
    assert.ok(fs.existsSync(configPath), "sauron.config.yaml must be created");

    // Assert: Verify multi-runtime adapter files are written
    const expectedFiles = [
      "CLAUDE.md",
      ".cursorrules",
      ".windsurfrules",
      ".clinerules",
      "GEMINI.md",
      path.join(".github", "copilot-instructions.md"),
      path.join(".cursor", "rules", "sauron.mdc"),
    ];

    for (const relFile of expectedFiles) {
      const fullPath = path.join(tempWorkspace, relFile);
      assert.ok(
        fs.existsSync(fullPath),
        `Expected runtime file '${relFile}' to be generated by E2E init`,
      );
      const content = fs.readFileSync(fullPath, "utf8");
      assert.ok(content.length > 50, `File '${relFile}' must not be empty`);
      assert.ok(
        content.includes("Sauron") || content.includes("sauron"),
        `File '${relFile}' must contain Sauron governance rules`,
      );
    }
  });

  it("verifies idempotency: re-running init preserves existing user config without crashing", async () => {
    // Act: Re-run sauron init on already initialized workspace
    const { stdout } = await execFileAsync("node", [CLI_PATH, "init"], {
      cwd: tempWorkspace,
    });

    // Assert: Check idempotency detection message
    assert.ok(
      stdout.includes("Existing sauron.config.yaml detected"),
      "Should recognize existing config and preserve state",
    );

    // Assert: Verify files remain intact
    assert.ok(fs.existsSync(path.join(tempWorkspace, "CLAUDE.md")));
    assert.ok(fs.existsSync(path.join(tempWorkspace, ".cursorrules")));
  });
});
