/**
 * @fileoverview Codex adapter generating .codex/instructions.md file.
 */

import type {
  RuntimeAdapter,
  TranspileContext,
  TranspileOutput,
} from "./types.js";

export class CodexAdapter implements RuntimeAdapter {
  public readonly id = "codex";
  public readonly name = "Codex";
  public readonly targetFiles = [".codex/instructions.md"];

  public transpile(context: TranspileContext): TranspileOutput[] {
    const lines: string[] = [];

    lines.push(`# Codex System Instructions for ${context.projectName}`);
    lines.push(`Generated by Sauron v${context.version}`);
    lines.push("");
    lines.push("## Coding Axioms");
    for (const rule of context.rules) {
      lines.push(`- ${rule}`);
    }
    lines.push("");
    lines.push("## Fellowship Sub-Agents Delegation Matrix");
    for (const agent of context.fellowship) {
      lines.push(`- ${agent.name} (${agent.role}): ${agent.slashCommand}`);
    }
    lines.push("");
    lines.push("## Anti-Patterns Guardrails");
    for (const ap of context.antiPatterns) {
      lines.push(`- ${ap}`);
    }
    lines.push("");

    return [
      {
        relativePath: ".codex/instructions.md",
        content: lines.join("\n"),
        format: "markdown",
      },
    ];
  }
}
