/**
 * @fileoverview Hermes adapter generating .hermesrules file.
 */

import {
  formatCavemanSection,
  type RuntimeAdapter,
  type TranspileContext,
  type TranspileOutput,
} from "./types.js";

export class HermesAdapter implements RuntimeAdapter {
  public readonly id = "hermes";
  public readonly name = "Hermes";
  public readonly targetFiles = [".hermesrules"];

  public transpile(context: TranspileContext): TranspileOutput[] {
    const lines: string[] = [];

    lines.push(`# .hermesrules for ${context.projectName}`);
    lines.push(`Generated by Sauron v${context.version}`);
    lines.push("");
    lines.push("## Directives");
    for (const rule of context.rules) {
      lines.push(`- ${rule}`);
    }
    lines.push("");
    lines.push(...formatCavemanSection("##"));
    lines.push("## Fellowship Matrix");
    for (const agent of context.fellowship) {
      lines.push(`- ${agent.name} (${agent.role}): ${agent.slashCommand}`);
    }
    lines.push("");
    lines.push("## Anti-Patterns Enforced");
    for (const ap of context.antiPatterns) {
      lines.push(`- ${ap}`);
    }
    lines.push("");

    return [
      {
        relativePath: ".hermesrules",
        content: lines.join("\n"),
        format: "text",
      },
    ];
  }
}
