/**
 * @fileoverview Windsurf adapter generating .windsurfrules file.
 */

import {
  formatCavemanSection,
  type RuntimeAdapter,
  type TranspileContext,
  type TranspileOutput,
} from "./types.js";

export class WindsurfAdapter implements RuntimeAdapter {
  public readonly id = "windsurf";
  public readonly name = "Windsurf";
  public readonly targetFiles = [".windsurfrules"];

  public transpile(context: TranspileContext): TranspileOutput[] {
    const lines: string[] = [];

    lines.push(`# .windsurfrules : ${context.projectName}`);
    lines.push(`Generated by Sauron v${context.version}`);
    lines.push("");
    lines.push("## Character and Persona");
    lines.push(
      "Operate as a senior polyglot software engineer strictly adhering to Sauron governance.",
    );
    lines.push("");
    lines.push("## Architectural Constraints");
    for (const rule of context.rules) {
      lines.push(`- ${rule}`);
    }
    lines.push("");
    lines.push(...formatCavemanSection("##"));
    lines.push("## Fellowship Sub-Agents Execution Hierarchy");
    for (const agent of context.fellowship) {
      lines.push(
        `- ${agent.name} [${agent.role}] : invoke with ${agent.slashCommand}`,
      );
    }
    lines.push("");
    lines.push("## Skills Catalog");
    for (const skill of context.skills) {
      lines.push(`- ${skill.triggerCommand} -> ${skill.name}`);
    }
    lines.push("");
    lines.push("## Blocked Anti-Patterns");
    for (const ap of context.antiPatterns) {
      lines.push(`- ${ap}`);
    }
    lines.push("");

    return [
      {
        relativePath: ".windsurfrules",
        content: lines.join("\n"),
        format: "text",
      },
    ];
  }
}
